// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rebbuweehpcopwcskhkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlYmJ1d2VlaHBjb3B3Y3NraGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzYyNDcsImV4cCI6MjA3NDAxMjI0N30.LKQ-0C-QLjz5agcW475Hoto9hrGVIMRJ9cw7FchAqQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});